services:
  - type: web
    name: taskmgr
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: taskmgr
      - key: PYTHON_VERSION
        value: "3.11"
